[database]
hostname = "localhost"
port = 3306
username = "dbuser"
password = "user_password"
database = "timeseries"

[httpServer]
port = 8080

[redis]
env = "dev"
hostname = "localhost"
port = 6379

[app]
env = "dev"