[database]
hostname = "localhost"
port = 3307
username = "dbuser"
password = "user_password"
database = "timeseries"

[httpServer]
port = 8080

[redis]
hostname = "localhost"
port = 6379

[app]
env = "demo"
seriesGroups = ["ECG"]

