mysql:
  image: yobasystems/alpine-mariadb
  environment:
    MYSQL_ROOT_PASSWORD: root_password
    MYSQL_DATABASE: timeseries
    MYSQL_USER: dbuser
    MYSQL_PASSWORD: user_password
  expose:
    - "3306"
  ports:
    - "3306:3306"
  volumes:
    - ./data/mysql:/var/lib/mysql
  restart: always

redis:
  image: redis:5.0.2-alpine
  expose:
    - "6379"
  ports:
    - "6379:6379"
  restart: always

