# mysql:
#   image: yobasystems/alpine-mariadb
#   command: ['--max_allowed_packet=2G']
#   environment:
#     MYSQL_ROOT_PASSWORD: root_password
#     MYSQL_DATABASE: timeseries
#     MYSQL_USER: dbuser
#     MYSQL_PASSWORD: user_password
#   expose:
#     - "3306"
#   ports:
#     - "3306:3306"
#   volumes:
#     - ./data/mysql:/var/lib/mysql
#   command: --innodb_buffer_pool_size=1G --innodb_read_only=1 
#   restart: always

  # mysql-index-test:
  #   image: yobasystems/alpine-mariadb
  #   command: ['--max_allowed_packet=2G']
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root_password
  #     MYSQL_DATABASE: timeseries
  #     MYSQL_USER: dbuser
  #     MYSQL_PASSWORD: user_password
  #   expose:
  #     - "3306"
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - ./data/mysql-index-test:/var/lib/mysql
  #   restart: always
  # 
  # mysql-query-test:
  #   image: yobasystems/alpine-mariadb
  #   command: ['--max_allowed_packet=2G']
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root_password
  #     MYSQL_DATABASE: timeseries
  #     MYSQL_USER: dbuser
  #     MYSQL_PASSWORD: user_password
  #   expose:
  #     - "3306"
  #   ports:
  #     - "3308:3306"
  #   volumes:
  #     - ./data/mysql-query-test:/var/lib/mysql
  #   restart: always

redis:
  image: redis:5.0.2-alpine
  expose:
    - "6379"
  ports:
    - "6379:6379"
  restart: always

